repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude_types: [css, markdown, text, svg]
      - id: trailing-whitespace
        exclude_types: [html, markdown, text]
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.285"
    hooks:
      - id: ruff
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        name: pydocstyle
        entry: pydocstyle
        language: python
        types: [python]
        files: '^openbb_fd/.*\.py$'
        exclude: 'tests/.*\.py|openbb_fd/test_.*\.py'
        args: ["--config=pyproject.toml"]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        entry: codespell
        args:
          [
            "--ignore-words-list=fd",
            "--quiet-level=2",
            "--skip=./**/tests/**,./**/test_*.py,.git,*.css,*.csv,*.html,*.ini,*.ipynb,*.js,*.json,*.lock,*.scss,*.txt,*.yaml",
            "-x=.github/workflows/linting.yml"
          ]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        description: ""
        entry: mypy
        language: python
        "types_or": [python, pyi]
        args: ["--ignore-missing-imports", "--scripts-are-modules"]
        require_serial: true
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        name: Strip notebooks output
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args:
          [
            "--baseline",
            ".secrets.baseline",
            "--exclude-files",
            "cassettes/.*|record/.*",
          ]
    exclude: package.lock.json
